### ISSUE TITLE
KeyError: 'pykakasi/hepburnhira2.pickle'

### ISSUE THREAD

**Issue by bjlaur** [miurahr/pykakasi#17]
I get this error when doing a trivial test like what's listed here:
https://pypi.python.org/pypi/pykakasi

This is on a --user install by the way.

**Comment by miurahr** [comment]
I've try to reproduce and got another error. It seems a same cause.

using python 2.7.10 and `easy_install pykakasi`, run `nosetests` with  test case on `tests`

```
======================================================================
ERROR: test_kakasi_hepburn (test_pykakasi.TestPyKakasi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/miurahr/projects/pykakasi-test/test_pykakasi.py", line 33, in test_kakasi_hepburn
    converter  = kakasi.getConverter()
  File "build/bdist.linux-x86_64/egg/pykakasi/kakasi.py", line 119, in getConverter
    self._conv["J"] = J2a(method = self._option["r"])
  File "build/bdist.linux-x86_64/egg/pykakasi/j2a.py", line 38, in __init__
    self._jconv = J2H()
  File "build/bdist.linux-x86_64/egg/pykakasi/j2h.py", line 46, in __init__
    self._kanwa = kanwa()
  File "build/bdist.linux-x86_64/egg/pykakasi/kanwa.py", line 35, in __init__
    dictpath = resource_filename(__name__, 'kanwadict2.db')
  File "/home/miurahr/.pyenv/versions/pykakasi27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1155, in resource_filename
    self, resource_name
  File "/home/miurahr/.pyenv/versions/pykakasi27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1852, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/home/miurahr/.pyenv/versions/pykakasi27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1873, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'pykakasi/kanwadict2.db'
```

**Comment by eromoe** [comment]
pip install same error here.
Even latest version, installed by `python setup.py install`.

**Comment by kisuka** [comment]
In setup.py change _pre_build to pre_build.

Then do:
```
python setup.py build
python setup.py install
python setup.py clean
```

**Comment by miurahr** [comment]
fix released
