### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by miurahr** [miurahr/pykakasi#18]
```
(pykakasi)miurahr@:~/projects/pykakasi-test$ pip install pykakasi
Collecting pykakasi
/home/miurahr/.pyenv/versions/pykakasi/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pykakasi-0.23.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 178kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-0fGo1u/pykakasi/setup.py", line 8, in <module>
        import nose
    ImportError: No module named nose

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0fGo1u/pykakasi
```

**Comment by miurahr** [comment]
it is happen when python 2.6.9

**Comment by miurahr** [comment]
b13c32bcaf0ff8e7d6668e3ca57edc6603bac89e fix it.  waiting release.

**Comment by sinshutu** [comment]
I tried
```
pip install pykakasi
```
ImportError: No module named nose

But,
```
pip install git+https://github.com/miurahr/pykakasi
```
Success

There is a possibility that registration to P is something wrong??

**Comment by loganknecht** [comment]
Hi there @miurahr 

Just sharing that I'm experiencing this as well and would love a fix for this.

I really love your project! It's been super helpful for my personal projects!

**Comment by miurahr** [comment]
fix released
