### ISSUE TITLE
Need flag to open new db

### ISSUE THREAD

**Issue by vladkorotnev** [miurahr/pykakasi#23]
```
Traceback (most recent call last):
  File "/root/kakasi-test.py", line 14, in <module>
    conv = kakasi.getConverter()
  File "/usr/local/lib/python2.7/dist-packages/pykakasi/kakasi.py", line 119, in getConverter
    self._conv["J"] = J2a(method = self._option["r"])
  File "/usr/local/lib/python2.7/dist-packages/pykakasi/j2a.py", line 38, in __init__
    self._jconv = J2H()
  File "/usr/local/lib/python2.7/dist-packages/pykakasi/j2h.py", line 46, in __init__
    self._kanwa = kanwa()
  File "/usr/local/lib/python2.7/dist-packages/pykakasi/kanwa.py", line 36, in __init__
    self._kanwadict = dbm.open(dictpath,'r')
  File "/usr/lib/python2.7/anydbm.py", line 79, in open
    raise error, "need 'c' or 'n' flag to open new db"
anydbm.error: need 'c' or 'n' flag to open new db
```

**Comment by vladkorotnev** [comment]
I tried to install via PIP, but it didn't produce the dictionary database. Then I downloaded the Git repository and run setup.py genkanwa, and copied the generated files into the specified location, and this error happened. So I deleted the PIP version completely, and run setup.py genkanwa again, and then setup.py install. Then the problem was gone. 

// Ak.R.

iOS/Mac/Windows & Web developer
Vaporwave/ambient producer, sound/video engineer

Genjitsu Gadget Lab Member 001
http://genjit.su

**Comment by miurahr** [comment]
Thank you for a report. It would be a bug on PIP version so it is necessary to update pip upload file.

**Comment by miurahr** [comment]
same as #17 ?

**Comment by miurahr** [comment]
I think v0.80  fixed this. Cloud you try it again?
