### ISSUE TITLE
Test failed on Windows

### ISSUE THREAD

**Issue by miurahr** [miurahr/pykakasi#27]
from https://ci.appveyor.com/project/miurahr/pykakasi/build/1.0.27/job/kb83k9v66xjqwq0r

```
183 ======================================================================
184 ERROR: test_mkdict (tests.test_genkanwadict.TestGenkanwadict)
185 ----------------------------------------------------------------------
186 Traceback (most recent call last):
187  File "C:\projects\pykakasi\tests\test_genkanwadict.py", line 28, in test_mkdict
188    self.kanwa.mkdict(src, dst)
189  File "C:\projects\pykakasi\pykakasi\genkanwadict\mkkanwa.py", line 41, in mkdict
190    dump((dic, max_key_len), open(dst, 'wb'), protocol=2)
191IOError: [Errno 2] No such file or directory: '/tmp\\test_kanadict.pickle'
192
193 ======================================================================
194 ERROR: test_mkkanwa (tests.test_genkanwadict.TestGenkanwadict)
195 ----------------------------------------------------------------------
196 Traceback (most recent call last):
197  File "C:\projects\pykakasi\tests\test_genkanwadict.py", line 42, in test_mkkanwa
198    self.kanwa.run(src, dst)
199  File "C:\projects\pykakasi\pykakasi\genkanwadict\mkkanwa.py", line 21, in run
200    self.kanwaout(dst)
201  File "C:\projects\pykakasi\pykakasi\genkanwadict\mkkanwa.py", line 71, in kanwaout
202    dic = dbm.open(out, 'c')
203  File "c:\python27\Lib\anydbm.py", line 85, in open
204    return mod.open(file, flag, mode)
205  File "c:\python27\Lib\dbhash.py", line 18, in open
206    return bsddb.hashopen(file, flag, mode)
207  File "c:\python27\Lib\bsddb\__init__.py", line 364, in hashopen
208    d.open(file, db.DB_HASH, flags, mode)
209 DBNoSuchFileError: (2, 'No such file or directory')
210
211----------------------------------------------------------------------
212Ran 29 tests in 0.140s
```

**Comment by miurahr** [comment]
fixed by #29
