### ISSUE TITLE
install from git repository make error

### ISSUE THREAD

**Issue by miurahr** [miurahr/pykakasi#35]
```
(venv) :~/projects/test-pykakasi$ pip install git+https://github.com/miurahr/pykakasi
Collecting git+https://github.com/miurahr/pykakasi
  Cloning https://github.com/miurahr/pykakasi to /tmp/pip-ow0_xkl1-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ow0_xkl1-build/setup.py", line 9, in <module>
        import pykakasi.genkanwadict as genkanwadict
      File "/tmp/pip-ow0_xkl1-build/pykakasi/__init__.py", line 1, in <module>
        from .a2 import a2
      File "/tmp/pip-ow0_xkl1-build/pykakasi/a2.py", line 7, in <module>
        from six import unichr
    ModuleNotFoundError: No module named 'six'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ow0_xkl1-build/
```

**Comment by miurahr** [comment]
Readme: Update documentation
