### ISSUE TITLE
Fullwitdh colon \u11fa causes Exception on conv.do()

### ISSUE THREAD

**Issue by 10000shiro** [miurahr/pykakasi#51]
Similar behaviour to issue #46 but for the character Fullwidth colon \uff1a.
Possibly more characters affected.

**Comment by miurahr** [comment]
\uFF1A ?
https://www.unicode.org/charts/PDF/UFF00.pdf

**Comment by miurahr** [comment]
I've added test case
```
    def test_kakasi_special_chars(self):
        TESTS = [
            ("", ""),
            ("\uFF1A", ":")
        ]

        kakasi = pykakasi.kakasi()
        kakasi.setMode("H","a")
        kakasi.setMode("K","a")
        kakasi.setMode("J","a")
        kakasi.setMode("r","Kunrei")
        kakasi.setMode("E","a")
        kakasi.setMode("s", True)
        kakasi.setMode("a", None)
        kakasi.setMode("C", True)
        converter  = kakasi.getConverter()
        for case, result in TESTS:
            self.assertEqual(converter.do(case), result)
```
and got
```

======================================================================
ERROR: test_kakasi_special_chars (tests.test_exceptions.TestPyKakasiExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/miurahr/projects/pykakasi/tests/test_exceptions.py", line 34, in test_kakasi_special_chars
    self.assertEqual(converter.do(case), result)
  File "/home/miurahr/projects/pykakasi/pykakasi/kakasi.py", line 240, in do
    otext = otext + self._conv["E"].convert(text[i])
TypeError: must be str, not NoneType

----------------------------------------------------------------------
```

**Comment by miurahr** [comment]
Thanks @10000shiro  for your report!  I found a conditional bug and fixed it.
