### ISSUE TITLE
KeyError with specific character

### ISSUE THREAD

**Issue by PicoSushi** [miurahr/pykakasi#68]
A bad character causes KeyError in pykakasi.
```python
from pykakasi import kakasi


def text_convert():
    bad_char = ""
    print(ord(bad_char))
    kks = kakasi()
    kks.setMode("J", "H")
    convert = kks.getConverter()

    text = convert.do(bad_char)
    print(text)


if __name__ == "__main__":
    text_convert()
```
results
```
57496
Traceback (most recent call last):
  File "/tmp/pyk.py", line 16, in <module>
    text_convert()
  File "/tmp/pyk.py", line 11, in text_convert
    text = convert.do(bad_char)
  File "/home/picosushi/pyenv/py3/lib/python3.7/site-packages/pykakasi/kakasi.py", line 146, in do                                                                     
    (t, l1) = self._conv[mode].convert(text[i:w])
  File "/home/picosushi/pyenv/py3/lib/python3.7/site-packages/pykakasi/j2.py", line 80, in convert_H                                                                   
    table = self._kanwa.load(text[0])
  File "/home/picosushi/pyenv/py3/lib/python3.7/site-packages/pykakasi/kanwa.py", line 40, in load                                                                     
    self._jisyo_table[key] = loads(decompress(self._kanwadict[key]))
  File "/home/picosushi/pyenv/py3/lib/python3.7/site-packages/semidbm/db.py", line 93, in __getitem__                                                                  
    offset, size = self._index[key]
KeyError: b'e098'
```

NOTE: This issue is from [python - pykakasiで文字列置き換えの際にKeyErrorが発生する - スタック・オーバーフロー](https://ja.stackoverflow.com/questions/53689/pykakasi%e3%81%a7%e6%96%87%e5%ad%97%e5%88%97%e7%bd%ae%e3%81%8d%e6%8f%9b%e3%81%88%e3%81%ae%e9%9a%9b%e3%81%abkeyerror%e3%81%8c%e7%99%ba%e7%94%9f%e3%81%99%e3%82%8b) .

**Comment by PicoSushi** [comment]
And, this error was caused in Python 3.7.

**Comment by miurahr** [comment]
It should not be raise error when getting bad characters, it may ignore silently.

**Comment by miurahr** [comment]
The character seems \uE098 that is in private use code(PUC) area.
It should be ignored by pykakasi

**Comment by miurahr** [comment]
Why it comes in j2:80, 
```python
    def isRegion(self, c):
        return 0x3400 <= ord(c[0]) < 0xfa2e
```
has  a PUC  area \ue0000-f8ff  

it should be

```python
    def isRegion(self, c):
        return 0x3400 <= ord(c[0]) < 0xe000 or  0xf900 <= ord(c[0]) 0xfa2e
```

**Comment by harpaj** [comment]
We ran into the same problem with character \u57C7:
```
>>> import pykakasi
>>> kks = pykakasi.kakasi()
>>> kks.setMode("J", "H")
>>> convert = kks.getConverter()
>>> convert.do("埇")
```
results in 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/pykakasi/kakasi.py", line 146, in do
    (t, l1) = self._conv[mode].convert(text[i:w])
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/pykakasi/j2.py", line 80, in convert_H
    table = self._kanwa.load(text[0])
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/pykakasi/kanwa.py", line 40, in load
    self._jisyo_table[key] = loads(decompress(self._kanwadict[key]))
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/semidbm/db.py", line 93, in __getitem__
    offset, size = self._index[key]
KeyError: b'57c7'
```

**Comment by harpaj** [comment]
Hi @miurahr,
first, thanks for the quick fix of this problem. While it does work for the character I reported above now, I found a new character for which it still failed with the new version, its `\u6F51` (潑):

```
>>> import pykakasi
>>> kks = pykakasi.kakasi()
>>> kks.setMode("J", "H")
>>> convert = kks.getConverter()
>>> convert.do("埇")
'よう'
>>> convert.do("潑")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/pykakasi/kakasi.py", line 145, in do
    (t, l1) = self._conv[mode].convert(text[i:w])
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/pykakasi/j2.py", line 80, in convert_H
    table = self._kanwa.load(text[0])
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/pykakasi/kanwa.py", line 41, in load
    self._jisyo_table[key] = loads(decompress(self._kanwadict[key]))
  File "/home/johannes/matching_pipeline/venv/lib/python3.7/site-packages/semidbm/db.py", line 93, in __getitem__
    offset, size = self._index[key]
KeyError: b'6f51'
```

**Comment by harpaj** [comment]
@miurahr, thank you very much for the quick fix. I just tested the new version with the full dataset I had at hand, it worked without any problems.

I left out one piece of information from the list of failures above: The two characters `\u9ad9` and `\u73c9` were at least in this dataset by far the most frequent ones (each appearing a few hundred times while the others appeared only very rarely).

Potentially you could add transliterations for these two characters instead of skipping them? It's not important, I just thought that this might be interesting to you.

I would provide a PR, but I don't speak Japanese so I can't help with this.
Again, thanks for your work on this library, it is extremely useful!
