### ISSUE TITLE
v1.1にアップデート後、「゛ー」が異常終了する

### ISSUE THREAD

**Issue by Tsutomu-Ikeda** [miurahr/pykakasi#85]
```
$ python
Python 3.7.3 (default, Apr  8 2019, 13:30:19) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykakasi
>>> pykakasi.__version__
'1.1'
>>> kakasi = pykakasi.kakasi()
>>> 
>>> kakasi.setMode("H", "a")
>>> kakasi.setMode("K", "a")
>>> kakasi.setMode("J", "a")
>>> 
>>> kakasi.setMode("r", "Hepburn")
>>> 
>>> kakasi.setMode("s", True)
>>> kakasi.setMode("C", True)
>>> 
>>> conv = kakasi.getConverter()
>>> conv.do("バー")
'baa'
>>> conv.do("ハ゛ー")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "******************/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pykakasi/kakasi.py", line 147, in do
    chunk = chunk + chunk[-1]
IndexError: string index out of range
>>> 
```

**Comment by miurahr** [comment]
@ta9ya  How do you think?

**Comment by ta9ya** [comment]
Yes, I know that problem, but I don't fix yet.

The cause of this problem is not considering that characters other than hiragana and katakana come before the '-'.
It's same as this skipped test:
https://github.com/miurahr/pykakasi/blob/bfd5a919154eab165ea5bd0d2ea17294ca68bc1a/tests/test_pykakasi.py#L509-L522

**Comment by miurahr** [comment]
fix pushed 920e5eedbce57988a309e7bf16de5502cd75860d

**Comment by miurahr** [comment]
一旦、ワークアラウンドとしてchunkの長さチェックおよび、強制的な "-" への変換を導入しました。
 As a quick and dirty workaround, insert chunk length check. When first character is kana-dash, it force to convert to roman-dash.

**Comment by miurahr** [comment]
@Tsutomu-Ikeda エラー終了はしなくなりました。期待した動作になりましたでしょうか？

**Comment by Tsutomu-Ikeda** [comment]
LGTM 920e5ee
@miurahr ご対応ありがとうございます。異常終了することはなくなりました。
「ハ゛ー 」→「baa」となることが期待している動作ですが、こちらは別件ですので一旦クローズいたします。
```
$ python
Python 3.7.3 (default, Jun 18 2019, 23:51:39)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykakasi
>>> pykakasi.__version__
'1.2'
>>> kakasi = pykakasi.kakasi()
>>>
>>> kakasi.setMode("H", "a")
>>> kakasi.setMode("K", "a")
>>> kakasi.setMode("J", "a")
>>>
>>> kakasi.setMode("r", "Hepburn")
>>>
>>> kakasi.setMode("s", True)
>>> kakasi.setMode("C", True)
>>>
>>> conv = kakasi.getConverter()
>>> conv.do("バー")
'baa'
>>> conv.do("ハ゛ー")
'ha ゛ -'
>>>
```
